const mongoose = require('mongoose');

/**
 * One screen view, from one app session.
 *
 * The console kept reporting conversion as "not tracked" because nothing
 * counted visits — orders had no denominator. This is the denominator.
 *
 * Deliberately anonymous: a client-generated session id, the screen name and
 * the platform. No IP address, no device id, no name or email. `userId` is
 * filled only when the request already carried a signed-in token, so a
 * session can be tied to an account that chose to sign in and to nothing
 * otherwise.
 */
const visitEventSchema = new mongoose.Schema(
  {
    // Generated by the client per app launch. The unit a "visitor" is counted
    // in — distinct sessions, not distinct rows.
    sessionId: { type: String, required: true, index: true },

    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

    app: {
      type: String,
      enum: ['consumer', 'merchant', 'admin'],
      default: 'consumer',
    },
    platform: { type: String, default: 'unknown' },

    /// A route name, never a URL with parameters in it — '/product/:id', not
    /// '/product/68f…', so a screen name cannot become an identifier.
    screen: { type: String, default: '' },
  },
  { timestamps: true }
);

visitEventSchema.index({ createdAt: -1 });
visitEventSchema.index({ app: 1, createdAt: -1 });
visitEventSchema.index({ sessionId: 1, createdAt: -1 });

// Raw events expire after 90 days. The figures that matter are aggregates,
// and keeping every screen view forever grows without bound for no benefit.
visitEventSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 90 });

module.exports = mongoose.model('VisitEvent', visitEventSchema);
